// <auto-generated />
namespace EbDoc_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_has_record : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_has_record));
        
        string IMigrationMetadata.Id
        {
            get { return "201906241306474_add_has_record"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
