// <auto-generated />
namespace EbDoc_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedaccela_ids : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedaccela_ids));
        
        string IMigrationMetadata.Id
        {
            get { return "201905291150583_added accela_ids"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
