// <auto-generated />
namespace EbDoc_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedIs_MissingtoDocument : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedIs_MissingtoDocument));
        
        string IMigrationMetadata.Id
        {
            get { return "201905221844022_added Is_Missing to Document"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
